baseURL = 'https://elan-dcc.github.io/'
languageCode = 'en-GB'
title = 'ELAN'
copyright = 'Health Campus Den Haag'
theme = 'elancholia'
paginate = 2

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    title = "ELAN"
    languageName = "en-GB"
    LanguageCode = "en-GB"
    contentDir = "content"
    [languages.en.params]
      update = "Last update: 28-05-2024"
  [languages.nl]
    title = "ELAN"
    languageName = "nl-NL"
    LanguageCode = "nl-NL"
    contentDir = "content.nl"
    [languages.nl.params]
      update = "Laatste update: 24-04-2024"

[taxonomies]
authors = "authors"
year = "year"
themes = "themes"
datasources = "datasources"

[params]
# Dates are displayed following the format below. For more information about
# formatting, see https://gohugo.io/functions/format/
dateFormat = "2006-01-02"
themeStyle = 'style'


# I included the lang.merge to enable Dutch summaries for publications
# It's the most elegant way to support this imho - Lisette
[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'en'

[[module.mounts]]
source = 'content/nl'
target = 'content'
lang = 'nl'

[[module.mounts]]
source = 'content/en'
target = 'content'
lang = 'nl'


# Allow HTML in markdown files
# [markup.goldmark.renderer]
# unsafe = true