[[main]]
    identifier = "posts"
    name = "News"
    url = "/news/"
    weight = 10
[[main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 20
[[main]]
    identifier = "researchers"
    name = "Research Hub"
    url = "/researchers/"
    weight = 30

[[publication_menu]]
    identifier = "publications"
    name = "Per Year"
    url = "/publications/"
    weight = 1
[[publication_menu]]
    identifier = "authors"
    name = "Per author"
    url = "/authors/"
    weight = 2
[[publication_menu]]
    identifier = "themes"
    name = "Per theme/type"
    url = "/themes/"
    weight = 3

[[footer_menu]]
    identifier = "about_data"
    name = "About the data"
    url = "/about_data/"
    weight = 1
[[footer_menu]]
    identifier = "about_elan"
    name = "About ELAN"
    url = "/about_elan/"
    weight = 2
[[footer_menu]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 3
[[footer_menu]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 4
[[footer_menu]]
    identifier = "researchers"
    name = "Research Hub"
    url = "/researchers/"
    weight = 5